---
title: "Assignment"
author: "Gloria Stephen"
date: "2022-09-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Formulation of LP problem*
$$ \text{The objective function is Max}  \hspace{.3cm} Z = 420(L_1+L_2+L_3)+360(M_1+M_2+M_3)+300(S_1+S_2+S_3)$$
$$ \text{Rearraning the objective function Max}  \hspace{.3cm} Z = 420L_1 + 360M_1 + 300S_1 + 420L_2 + 360M_2 + 300S_2 + 420L_3 + 360M_3 + 300S_3 $$
subject to
$$L_1+M_1+S_1\le750$$
$$L_2+M_2+S_2\le900$$
$$L_3+M_3+S_3\le450 $$
$$20L_1+15M_1+12S_1\le13000$$
$$20L_2+15M_2+12S_2\le12000$$
$$20L_3+15M_3+12S_3\le5000$$
$$L_1+L_2+L_3\le900$$
$$M_1+M_2+M_3\le1200$$
$$S_1+S_2+S_3\le750$$
Non negativity constraints
$$L_1, L_2, L_3, M_1, M_2, M_3, S_1, S_2, S_3\ge0 $$
*The above LP problem constaraints can be written as*
$$L_1+M_1+S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3\le750$$
$$0L_1+0M_1+0S_1+L_2+M_2+S_2+0L_3+0M_3+0S_3\le900$$
$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+L_3+M_3+S_3\le450$$
$$20L_1+15M_1+12S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3\le13000$$
$$0L_1+0M_1+0S_1+20L_2+15M_2+12S_2+0L_3+0M_3+0S_3\le12000$$
$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+20L_3+15M_3+12S_3\le5000$$
$$L_1+0M_1+0S_1+L_2+0M_2+0S_2+L_3+0M_3+0S_3\le900$$
$$0L_1+M_1+0S_1+0L_2+M_2+0S_2+0L_3+M_3+0S_3\le1200$$
$$0L_1+0M_1+S_1+0L_2+0M_2+S_2+0L_3+0M_3+S_3\le750$$

```{r}

library(lpSolve)
library(tinytex)
```




```{r}
#Objective function 

f.obj <- c(420,360,300,420,360,300,420,360,300) 

#Constraints 

f.con<-matrix(c(1, 1, 1, 0, 0, 0, 0, 0, 0,

                0, 0, 0, 1, 1, 1, 0, 0, 0,  

                0, 0, 0, 0, 0, 0, 1, 1, 1, 

               20, 15, 12, 0, 0, 0, 0, 0, 0, 

               0, 0, 0, 20, 15, 12, 0, 0, 0,

               0, 0, 0, 0, 0, 0, 20, 15, 12,

                1, 0, 0, 1, 0, 0, 1, 0, 0,

                0, 1, 0, 0, 1, 0, 0, 1, 0,

                0, 0, 1, 0, 0, 1, 0, 0, 1), nrow = 9, byrow =TRUE) 

#set inequality signs 

f.dir<-c("<=", 

        "<=", 

        "<=",
        
        "<=",
        
        "<=",
        
        "<=",
        
        "<=",
        
        "<=",
        
        "<=")

#Set right hand side coefficients 

f.rhs <- c(750, 900, 450, 13000, 12000, 5000, 900, 1200, 750) 

#Value of Z 
lp("max", f.obj, f.con, f.dir, f.rhs) 

## Success: the objective function is 22.5 

#Values of the variables 

lp("max", f.obj, f.con, f.dir, f.rhs)$solution 
```

